import { expect, test } from '@playwright/test'
import { AxeBuilder } from '@axe-core/playwright'
import { openAddBabyDialog, registerAndLogin, uniqueTestUser } from './support/fixtures.js'

test('dated profile measurements survive reload and appear in growth', async ({ page }) => {
  await registerAndLogin(page, uniqueTestUser('measurements'))
  await openAddBabyDialog(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const dialog = page.getByRole('dialog')
  await page.getByLabel('Nome da Criança').fill('Alice Medidas')
  await page.getByLabel('Data de Nascimento').fill('2024-03-10')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Cor 4' }).click()
  await expect(page.getByTestId('avatar-preview')).toHaveCSS('background-color', 'rgb(105, 80, 199)')
  await page.screenshot({ path: 'docs/verification/child-editor-desktop-profile.png', style: '[data-sonner-toaster]{visibility:hidden}' })
  const before = await dialog.boundingBox()
  await page.getByRole('button', { name: 'Continuar' }).click()
  expect((await dialog.boundingBox())?.height).toBe(before?.height)
  await page.getByLabel('Peso (kg)').fill('3,5')
  await page.getByLabel('Altura (cm)').fill('50,5')
  await page.getByLabel('Data da medição').fill('2024-03-10')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: 'docs/verification/child-editor-desktop-health.png', style: '[data-sonner-toaster]{visibility:hidden}' })
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: 'docs/verification/child-editor-mobile-health.png', style: '[data-sonner-toaster]{visibility:hidden}' })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('[role="dialog"]').analyze()).violations).toEqual([])
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByLabel('Data da medição').scrollIntoViewIfNeeded()
  await expect(page.getByLabel('Data da medição')).toBeInViewport()
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.evaluate("document.documentElement.classList.add('dark')")
  expect((await new AxeBuilder({ page }).include('[role="dialog"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: 'docs/verification/child-editor-dark-health.png', style: '[data-sonner-toaster]{visibility:hidden}' })
  await page.evaluate("document.documentElement.classList.remove('dark')")
  await page.getByRole('button', { name: 'Criar Perfil' }).click()
  await expect(dialog).toBeHidden()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Alice Medidas', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Editar perfil de Alice Medidas' }).click()
  await page.getByRole('button', { name: /02.*Saúde/ }).click()
  await expect(dialog.getByText('3,5 kg · 50,5 cm')).toBeVisible()
  await page.getByRole('button', { name: 'Registrar nova medida' }).click()
  await page.getByLabel('Peso (kg)').fill('4,2')
  await page.getByLabel('Data da medição').fill('2024-04-10')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Salvar Alterações' }).click()
  await expect(dialog).toBeHidden()
  await page.goto('/crescimento')
  await expect(page.getByText('3,5 kg', { exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: '4,2 kg', exact: true })).toBeVisible()
})
