import { expect, test } from '@playwright/test'
import { AxeBuilder } from '@axe-core/playwright'
import { addBaby, openAddBabyDialog, registerAndLogin, uniqueTestUser } from './support/fixtures.js'

test('registers a vaccine with a local proof photo in a stable responsive dialog', async ({ page }) => {
  await registerAndLogin(page, uniqueTestUser('vaccine-proof'))
  await openAddBabyDialog(page)
  await addBaby(page, { name: 'Alice Vacinas', birthDate: '2024-03-10', sexAtBirth: 'Feminino' })
  await page.goto('/vaccines')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addStyleTag({ content: '*,*::before,*::after{animation:none!important;transition:none!important}' })
  await page.getByRole('button', { name: 'Registrar Vacina', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByText('Calendário obrigatório')).toBeVisible()
  const before = await dialog.boundingBox()
  await page.screenshot({ path: 'docs/verification/vaccine-types.png' })
  expect((await new AxeBuilder({ page }).include('[role="dialog"]').analyze()).violations).toEqual([])
  await dialog.getByText('Outra vacina').click()
  await dialog.getByLabel('Nome da vacina').fill('Vacina de teste')
  await dialog.getByLabel('Dose (Opcional)').fill('Reforço')
  await dialog.getByRole('button', { name: 'Continuar' }).click()
  expect((await dialog.boundingBox())?.height).toBe(before?.height)
  await page.screenshot({ path: 'docs/verification/vaccine-details-desktop.png' })
  const proof = await page.screenshot({ clip: { x: 0, y: 0, width: 100, height: 100 } })
  await dialog.locator('input[type=file]').setInputFiles({ name: 'proof.png', mimeType: 'image/png', buffer: proof })
  await expect(dialog.getByAltText('Prévia do comprovante')).toBeVisible()
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: 'docs/verification/vaccine-details-mobile.png' })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('[role="dialog"]').analyze()).violations).toEqual([])
  const response = page.waitForResponse(response => response.url().endsWith('/vaccines/adhoc') && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Salvar vacina' }).click()
  const saved = await response
  expect(saved.status()).toBe(201)
  const record = await saved.json()
  expect(record.photoUrl).toMatch(/^data:image\/jpeg;base64,/)
  await expect(dialog.getByRole('button', { name: 'Adicionar outra' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Concluir' }).click()
  const reloadedRecords = page.waitForResponse(response => response.url().endsWith('/vaccines/adhoc') && response.request().method() === 'GET')
  await page.reload()
  const records = await (await reloadedRecords).json()
  expect(records.find((item: { id: string }) => item.id === record.id).photoUrl).toBe(record.photoUrl)
  await expect(page.getByText('Vacina de teste', { exact: true })).toBeVisible()
})
